name: gemini_visual_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_ai: ^3.8.0
  camera: ^0.12.0
  image: ^4.2.0
  flutter_tts: ^4.2.2
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true
